### ISSUE TITLE
RMI deserialization vulnerability in RMIstart

### ISSUE THREAD

**Issue by artem-smotrakov** [NJU-Nonames/Logistics-System#1]
Hello,

What is the best way to report a potential security problem in this project? Unfortunately, I didn't find any security contact in the documentation. Thanks!

@Jiawei0227 @sanyangsanyang @tdy14 @qwertyuikj

**Comment by Jiawei0227** [comment]
Hello @artem-smotrakov ,
Thanks for reaching out. This project is just a school project that we did for fun. And it is not in any production or maintaining mode.

**Comment by artem-smotrakov** [comment]
Sure @Jiawei0227 I'll then post the details here. If someone would like to use the project, they could be aware of this.

**Comment by artem-smotrakov** [comment]
I noticed an RMI deserialization vulnerability. `RMIstart` registers multiple remote objects in the RMI registry:

https://github.com/NJU-Nonames/Logistics-System/blob/9f5d79c578efc7087679c70712bb50edeb898e97/Logistics_System/Server/src/main/java/data/RMIstart.java#L103

The registered remote objects have several methods with not-primitive parameters. RMI uses the default Java serialization mechanism for parameters in RMI invocations. A remote attacker can send a malicious serialized object to the above RMI entries. The objects get deserialized without any check on the incoming data. In the worst case, it may let the attacker to run arbitrary code remotely. You can find more details about this attack in the following articles

https://mogwailabs.de/en/blog/2019/03/attacking-java-rmi-services-after-jep-290/

https://itnext.io/java-rmi-for-pentesters-part-two-reconnaissance-attack-against-non-jmx-registries-187a6561314d

The issue can be mitigated by setting a process-wide filter for deserialization that was introduced in JEP 290

http://openjdk.java.net/jeps/290

The filter can be set via a system or security property. Unfortunately, there is no other way how the filter can be set for RMI.

Or, it may be better to replace RMI, for example, with other HTTP API + JSON (make sure that the underlying deserialization mechanism is safe).
